config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
    @navbar = true ###condition on partials
  end

  def create
   @flat = Flat.new(flat_params)
   @flat.save
   redirect_to flats_path
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="flat">
	<h1>Edit your flat</h1>
	<%= form_for(@flat) do |f| %>
	  <%= f.label :name%>
	  <br>
	  <%= f.text_field :name%>
	  <br>
	  <br>
	  <%= f.label :address %>
	  <br>
	  <%= f.text_field :address%>
	  <br>
	  <br>
	  <%= f.label :price_per_night%>
	  <br>
	  <%= f.text_field :price_per_night%>
	  <br>
	  <br>
	  <%= f.label :number_of_guests%>
	  <br>
	  <%= f.text_field :number_of_guests%>
	  <br>
	  <br>
	  <%= f.submit %>
	<% end %>
</div>

app/views/flats/index.html.erb
<h1><%= "All our Flats (" + @flats.length.to_s + ")" %></h1>
<div class="flats">
<% @flats.each do |flat| %>
    <div class="card">
	  <p><%= flat.name %></p>      
	  <p><%= flat.address %></p>
	  <p><i class="fas fa-users"><%= flat.number_of_guests %></i><i class="fas fa-dollar-sign"><%= flat.price_per_night %></i></p>
	  <%= link_to "More Info  ", flat_path(flat), class: "more-info" %>
      <br>
	  <%= link_to "Edit  ", edit_flat_path(flat), class: "edit" %>
      <br>
	  <%= link_to "Remove  ", flat_path(flat), method: :delete, class: "remove" %>
	</div>
	<% end %>
</div>

app/views/flats/new.html.erb
<div class="flat">
	<h1>Your new flat</h1>
	<%= form_for(@flat) do |f| %>
	  <%= f.label :name%>
	  <br>
	  <%= f.text_field :name%>
	  <br>
	  <br>
	  <%= f.label :address %>
	  <br>
	  <%= f.text_field :address %>
	  <br>
	  <br>
	  <%= f.label :price_per_night%>
	  <br>
	  <%= f.text_field :price_per_night%>
	  <br>
	  <br>
	  <%= f.label :number_of_guests%>
	  <br>
	  <%= f.text_field :number_of_guests%>
	  <br>
	  <br>
	  <%= f.submit %>
	<% end %>
</div>

app/views/flats/show.html.erb
<div class="flat">
  <h1><%= @flat.name %></h1>
  <h3><%= @flat.address %></h3>
    <div class="description">
      <h2>A little bit more about this flat..</h2>
	  <p><%= @flat.description %></p>      
	</div>
	<div class="details">
      <h2>Details</h2>
	  <p><i class="fas fa-users"><%= @flat.number_of_guests %></i><i class="fas fa-dollar-sign"><%= @flat.price_per_night %></i></p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">



    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar" unless @navbar %>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <h3>Simple Airbnb</h3>

  <!-- Right Navigation -->
  <div class="navbar-right hidden-xs hidden-sm">
    <%= link_to "Add Flat", new_flat_path, class: "navbar-item, navbar-link" %>
  </div>
</div>